name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: |
        npm install
        npm install -g typescript
        npm install -g eslint
    - name: Lint
      run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: |
        npm install
        npm install -g typescript
        npm install -g jest
    - name: Lint
      run: npm run test
